export const appStrings = {
    //header
    logo: "src/assets/images/header/logo.png",
    //banners
    bannerTitle1: "Virtual healthcare for you",
    bannerText1: "Our service provides progressive, and affordable healthcare, accessible on mobile and online for everyone",
    bannerButton1: "Consult today",
    bannerImage1: "src/assets/images/banners/banner1.png", 
    bannerTitle2: "Leading healthcare providers",
    bannerText2: "We provides progressive, and affordable healthcare, accessible on mobile and online for everyone. To us, it's not just work. We take pride in the solutions we deliver",
    bannerButton2: "Learn more",
    bannerImage2: "src/assets/images/banners/banner2.png",
    bannerTitle3: "Download our mobile apps",
    bannerText3: "Our dedicated patient engagement app and web portal allow you to access information instantaneously (no tedeous form, long calls, or administrative hassle) and securely",
    bannerButton3: "Download",
    bannerImage3: "src/assets/images/banners/banner3.png",
    //services
    SCTitle: "Our services",
    SCDescription: "We provide to you the best choiches for you. Adjust it to your health needs and make sure your undergo treatment with our highly qualified doctors you can consult with us which type of service is suitable for your health",
    SCTitle1: "Search doctor",
    SCDescription1: "Choose your doctor from thousands of specialist, general, and trusted hospitals",
    SCIcon1: "src/assets/images/serviceCards/doctor.png",
    SCTitle2: "Online pharmacy",
    SCDescription2: "Buy  your medicines with our mobile application with a simple delivery system",
    SCIcon2: "src/assets/images/serviceCards/pharmacy.png",
    SCTitle3: "Consultatuion",
    SCDescription3: "Free consultation with our trusted doctors and get the best recomendations",
    SCIcon3: "src/assets/images/serviceCards/consultation.png",
    SCTitle4: "Details info",
    SCDescription4: "Free consultation with our trusted doctors and get the best recomendations",
    SCIcon4: "src/assets/images/serviceCards/details.png",
    SCTitle5: "Emergency care",
    SCDescription5: "You can get 24/7 urgent care for yourself or your children and your lovely family",
    SCIcon5: "src/assets/images/serviceCards/care.png",
    SCTitle6: "Tracking",
    SCDescription6: "Track and save your medical history and health data ",
    SCIcon6: "src/assets/images/serviceCards/tracking.png",
}
